### ISSUE TITLE
common_parameters doesn't merge

### ISSUE THREAD

**Issue by hdep** [cirrax/puppet-postfix#2]
Hello,

I add to add this in my common.eyaml file :  

```
lookup_options:
    postfix::common_parameters:
      merge:
        strategy: deep

```

Without this I can't specifiy specific configuration at host level. 
Is this wanted ?
